[package]
name = "nodejs-binding-macro"
version = "0.1.0"
authors = ["Dmitriy Belyaev <mail@d-belyaev.ru>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0.11", features = ["full"]}
find-crate = "0.5.0"

